import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/homeview/NavBar"


export const metadata: Metadata = {
	title: "Jorge Sao | Habana Eventos",
	description: "Generated by create next app",
};

const bodyStyles = "min-h-screen";

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
	return (
		<html lang="es">
		<body className={bodyStyles}>
			<NavBar/>
			{children}
		</body>
		</html>
	);
}
